### ISSUE TITLE
retry.count config not working

### ISSUE THREAD

**Issue by bitstrider** [npm/npm-registry-client#162]
I'm setting the # of retry attempts like this:
```javascript
const RegClient = require('npm-registry-client')
const client = new RegClient({retry:{count:0}})
```
but the outcome is still the default behavior (2 retries)

npm-registry-client@8.4.0
OS: Windows 10

**Comment by mfellner** [comment]
The documentation is inaccurate. It should be `retries`, not `count`. See https://github.com/npm/npm-registry-client/blob/latest/index.js#L35.
