### ISSUE TITLE
ssl params ignored

### ISSUE THREAD

**Issue by madbence** [npm/npm-registry-client#98]
See npm/npm#7226.

[`initialize.js`](/npm/npm-registry-client/blob/master/lib/initialize.js) creates global agents. SSL params in the request are silently ignored because of this (according to [core docs](http://nodejs.org/docs/v0.11.15/api/https.html#https_https_request_options_callback)).

**Comment by othiym23** [comment]
Thanks. This is a regression due to 4701a29bcda41bc14aa91f361dd0d576e24677d7, which addresses a change in Node 0.11.x / io.js 1.0.x. I'm trying to get a fix out for this today.
